# 衛星データの取得方法(USGS)

## USGS EarthExplorerをダウンロード、登録/ログインする

## データを取得したい地域を設定する
+ 【Geocoder】のタブで【World Features】を選択する(米国内のデータを取得したい場合は、【US Features(デフォルト)】に設定)
+ 【Country】から【BANGLADESH】を選択
+ 【Show】を押下

+ 表示された表から、取得したい地域に近い/取得したい地域を選択する  

下図のように、右エリアにポイントが表示される

## データ取得領域をバングラデシュ全体に拡張する
【Polygon】  
+ データを取得したいエリアをポイントが取り囲むよう、各地点をクリックしていく
+ 選択したエリアが赤く表示される  

【Circle】  
+ データを取得したい地域を含むように、右地図上の2点を選択する
+ 選択した2点で描かれる円の範囲が赤く表示される

## データを取得したい日時を設定する
+ 【Date Range】から選択
(カレンダーから選択が可能)

## 雲の量を調整する
+ 【Cloud Cover】でバーを動かすことにより、設定が可能
＊ただし衛星データによっては雲量調整を行っていないものがあり、その場合は適用されない

## Data Setsを押下

##  必要なデータセットを選択する
+ データセットの中から必要なデータセットを選択する  
＊データセット名の左のインフォメーションマークを押下すると説明が出る  
＊データセット名の左の地図マークを押下すると、そのデータのカバー範囲が右地図上に表示される

## Resultsを押下する

## データのダウンロード
+【Show Brouwse Overlay】を押下すると、各データを右地図上に表示することができる  
＊複数のデータにわたる場合には、Acquisition Dateを確認する(データの詳細は【Show Mwtadata and Browse】から確認可能)
+ 必要なデータセット以外は、【Exclude Scene from Results】を押下
+ 【Click here to export your results】の【Export data】を押下し、【Export Name】、【Export Format】を設定する  
ダウンロード完了
